name: Run Pizzeria Autotests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Скачиваем код из репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Настраиваем Conda и разворачиваем окружение из environment.yml
      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: pizzeria-env # Название вашего conda-окружения
          environment-file: Final_project_Pizzeria/environment.yml
          auto-activate-base: false

      # 3. Переходим в директорию проекта и запускаем тесты
      - name: Run Pytest
        shell: bash -l {0} # Обязательно для корректной работы активированного Conda-окружения
        run: |
          cd Final_project_Pizzeria
          pytest -v