name: Run Autotests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Скачиваем код из репозитория
      - name: Checkout repository
        uses: actions/checkout@v5

      # 2. Настраиваем Conda и разворачиваем окружение из environment.yml
      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v4
        with:
          activate-environment: module_7_playwright # Название вашего conda-окружения
          environment-file: module_7_playwright/environment.yml
          auto-activate-base: false

      # 3. Переходим в директорию проекта и запускаем тесты
      - name: Run Pytest
        shell: bash -l {0} # Обязательно для корректной работы активированного Conda-окружения
        run: |
          cd module_7_playwright
          pytest -v